<?php
declare(strict_types=1);

namespace Demo;

class CountryMapper
{
    public static function mapCountry(?string $country): ?string
    {
        if ($country === null) {
            return null;
        }
        if (strlen($country) === 2) {
            if (array_key_exists($country, self::$countryISOMapping)) {
                return self::$countryISOMapping[$country];
            }
        } elseif (strlen($country) === 3) {
            $reverseResolve = array_flip(self::$countryISOMapping);
            if (array_key_exists($country, $reverseResolve)) {
                return $reverseResolve[$country];
            }
        }
        return null;
    }

    /**
     * @phpstan-param CountryIso3Enum::*|string|null $country
     */
    public static function mapCountry3To2(?string $country): ?string
    {
        if ($country === null || strlen($country) === 2) {
            return $country;
        }
        if (strlen($country) === 3) {
            $reverseResolve = array_flip(self::$countryISOMapping);
            $reverseResolve[CountryIso3Enum::GBR] = 'GB';
            if (array_key_exists($country, $reverseResolve)) {
                return $reverseResolve[$country];
            }
        }
        return null;
    }

    /**
     * @phpstan-return CountryIso3Enum::*|null
     */
    public static function mapCountry2To3(?string $country): ?string
    {
        if ($country === null || strlen($country) === 3) {
            /** @phpstan-var CountryIso3Enum::*|null $country */
            return $country;
        }
        return self::$countryISOMapping[$country] ?? null;
    }

    /**
     * @phpstan-var array<string,CountryIso3Enum::*>
     */
    private static array $countryISOMapping = [
        'AC' => CountryIso3Enum::ASC,
        'AD' => CountryIso3Enum::AND,
        'AE' => CountryIso3Enum::ARE,
        'AF' => CountryIso3Enum::AFG,
        'AG' => CountryIso3Enum::ATG,
        'AI' => CountryIso3Enum::AIA,
        'AL' => CountryIso3Enum::ALB,
        'AM' => CountryIso3Enum::ARM,
        'AN' => CountryIso3Enum::ANT,
        'AO' => CountryIso3Enum::AGO,
        'AQ' => CountryIso3Enum::ATA,
        'AR' => CountryIso3Enum::ARG,
        'AS' => CountryIso3Enum::ASM,
        'AT' => CountryIso3Enum::AUT,
        'AU' => CountryIso3Enum::AUS,
        'AW' => CountryIso3Enum::ABW,
        'AX' => CountryIso3Enum::ALA,
        'AZ' => CountryIso3Enum::AZE,
        'BA' => CountryIso3Enum::BIH,
        'BB' => CountryIso3Enum::BRB,
        'BD' => CountryIso3Enum::BGD,
        'BE' => CountryIso3Enum::BEL,
        'BF' => CountryIso3Enum::BFA,
        'BG' => CountryIso3Enum::BGR,
        'BH' => CountryIso3Enum::BHR,
        'BI' => CountryIso3Enum::BDI,
        'BJ' => CountryIso3Enum::BEN,
        'BL' => CountryIso3Enum::BLM,
        'BM' => CountryIso3Enum::BMU,
        'BN' => CountryIso3Enum::BRN,
        'BO' => CountryIso3Enum::BOL,
        'BQ' => CountryIso3Enum::BES,
        'BR' => CountryIso3Enum::BRA,
        'BS' => CountryIso3Enum::BHS,
        'BT' => CountryIso3Enum::BTN,
        'BU' => CountryIso3Enum::BUR,
        'BV' => CountryIso3Enum::BVT,
        'BW' => CountryIso3Enum::BWA,
        'BY' => CountryIso3Enum::BLR,
        'BZ' => CountryIso3Enum::BLZ,
        'CA' => CountryIso3Enum::CAN,
        'CC' => CountryIso3Enum::CCK,
        'CD' => CountryIso3Enum::COD,
        'CE' => CountryIso3Enum::CEE,
        'CF' => CountryIso3Enum::CAF,
        'CG' => CountryIso3Enum::COG,
        'CH' => CountryIso3Enum::CHE,
        'CI' => CountryIso3Enum::CIV,
        'CK' => CountryIso3Enum::COK,
        'CL' => CountryIso3Enum::CHL,
        'CM' => CountryIso3Enum::CMR,
        'CN' => CountryIso3Enum::CHN,
        'CO' => CountryIso3Enum::COL,
        'CP' => CountryIso3Enum::CPT,
        'CR' => CountryIso3Enum::CRI,
        'CS' => CountryIso3Enum::SCG,
        'CU' => CountryIso3Enum::CUB,
        'CV' => CountryIso3Enum::CPV,
        'CW' => CountryIso3Enum::CUW,
        'CX' => CountryIso3Enum::CXR,
        'CY' => CountryIso3Enum::CYP,
        'CZ' => CountryIso3Enum::CZE,
        'DE' => CountryIso3Enum::DEU,
        'DG' => CountryIso3Enum::DGA,
        'DJ' => CountryIso3Enum::DJI,
        'DK' => CountryIso3Enum::DNK,
        'DM' => CountryIso3Enum::DMA,
        'DO' => CountryIso3Enum::DOM,
        'DZ' => CountryIso3Enum::DZA,
        'EC' => CountryIso3Enum::ECU,
        'EE' => CountryIso3Enum::EST,
        'EG' => CountryIso3Enum::EGY,
        'EH' => CountryIso3Enum::ESH,
        'ER' => CountryIso3Enum::ERI,
        'ES' => CountryIso3Enum::ESP,
        'ET' => CountryIso3Enum::ETH,
        'FI' => CountryIso3Enum::FIN,
        'FJ' => CountryIso3Enum::FJI,
        'FK' => CountryIso3Enum::FLK,
        'FM' => CountryIso3Enum::FSM,
        'FO' => CountryIso3Enum::FRO,
        'FR' => CountryIso3Enum::FRA,
        'FX' => CountryIso3Enum::FXX,
        'GA' => CountryIso3Enum::GAB,
        'GB' => CountryIso3Enum::GBR,
        'GD' => CountryIso3Enum::GRD,
        'GE' => CountryIso3Enum::GEO,
        'GF' => CountryIso3Enum::GUF,
        'GG' => CountryIso3Enum::GGY,
        'GH' => CountryIso3Enum::GHA,
        'GI' => CountryIso3Enum::GIB,
        'GL' => CountryIso3Enum::GRL,
        'GM' => CountryIso3Enum::GMB,
        'GN' => CountryIso3Enum::GIN,
        'GP' => CountryIso3Enum::GLP,
        'GQ' => CountryIso3Enum::GNQ,
        'GR' => CountryIso3Enum::GRC,
        'GS' => CountryIso3Enum::SGS,
        'GT' => CountryIso3Enum::GTM,
        'GU' => CountryIso3Enum::GUM,
        'GW' => CountryIso3Enum::GNB,
        'GY' => CountryIso3Enum::GUY,
        'HK' => CountryIso3Enum::HKG,
        'HM' => CountryIso3Enum::HMD,
        'HN' => CountryIso3Enum::HND,
        'HR' => CountryIso3Enum::HRV,
        'HT' => CountryIso3Enum::HTI,
        'HU' => CountryIso3Enum::HUN,
        'ID' => CountryIso3Enum::IDN,
        'IE' => CountryIso3Enum::IRL,
        'IL' => CountryIso3Enum::ISR,
        'IM' => CountryIso3Enum::IMN,
        'IN' => CountryIso3Enum::IND,
        'IO' => CountryIso3Enum::IOT,
        'IQ' => CountryIso3Enum::IRQ,
        'IR' => CountryIso3Enum::IRN,
        'IS' => CountryIso3Enum::ISL,
        'IT' => CountryIso3Enum::ITA,
        'JE' => CountryIso3Enum::JEY,
        'JM' => CountryIso3Enum::JAM,
        'JO' => CountryIso3Enum::JOR,
        'JP' => CountryIso3Enum::JPN,
        'KE' => CountryIso3Enum::KEN,
        'KG' => CountryIso3Enum::KGZ,
        'KH' => CountryIso3Enum::KHM,
        'KI' => CountryIso3Enum::KIR,
        'KM' => CountryIso3Enum::COM,
        'KN' => CountryIso3Enum::KNA,
        'KP' => CountryIso3Enum::PRK,
        'KR' => CountryIso3Enum::KOR,
        'KW' => CountryIso3Enum::KWT,
        'KY' => CountryIso3Enum::CYM,
        'KZ' => CountryIso3Enum::KAZ,
        'LA' => CountryIso3Enum::LAO,
        'LB' => CountryIso3Enum::LBN,
        'LC' => CountryIso3Enum::LCA,
        'LI' => CountryIso3Enum::LIE,
        'LK' => CountryIso3Enum::LKA,
        'LR' => CountryIso3Enum::LBR,
        'LS' => CountryIso3Enum::LSO,
        'LT' => CountryIso3Enum::LTU,
        'LU' => CountryIso3Enum::LUX,
        'LV' => CountryIso3Enum::LVA,
        'LY' => CountryIso3Enum::LBY,
        'MA' => CountryIso3Enum::MAR,
        'MC' => CountryIso3Enum::MCO,
        'MD' => CountryIso3Enum::MDA,
        'ME' => CountryIso3Enum::MNE,
        'MF' => CountryIso3Enum::MAF,
        'MG' => CountryIso3Enum::MDG,
        'MH' => CountryIso3Enum::MHL,
        'MK' => CountryIso3Enum::MKD,
        'ML' => CountryIso3Enum::MLI,
        'MM' => CountryIso3Enum::MMR,
        'MN' => CountryIso3Enum::MNG,
        'MO' => CountryIso3Enum::MAC,
        'MP' => CountryIso3Enum::MNP,
        'MQ' => CountryIso3Enum::MTQ,
        'MR' => CountryIso3Enum::MRT,
        'MS' => CountryIso3Enum::MSR,
        'MT' => CountryIso3Enum::MLT,
        'MU' => CountryIso3Enum::MUS,
        'MV' => CountryIso3Enum::MDV,
        'MW' => CountryIso3Enum::MWI,
        'MX' => CountryIso3Enum::MEX,
        'MY' => CountryIso3Enum::MYS,
        'MZ' => CountryIso3Enum::MOZ,
        'NA' => CountryIso3Enum::NAM,
        'NC' => CountryIso3Enum::NCL,
        'NE' => CountryIso3Enum::NER,
        'NF' => CountryIso3Enum::NFK,
        'NG' => CountryIso3Enum::NGA,
        'NI' => CountryIso3Enum::NIC,
        'NL' => CountryIso3Enum::NLD,
        'NO' => CountryIso3Enum::NOR,
        'NP' => CountryIso3Enum::NPL,
        'NR' => CountryIso3Enum::NRU,
        'NT' => CountryIso3Enum::NTZ,
        'NU' => CountryIso3Enum::NIU,
        'NZ' => CountryIso3Enum::NZL,
        'OM' => CountryIso3Enum::OMN,
        'PA' => CountryIso3Enum::PAN,
        'PE' => CountryIso3Enum::PER,
        'PF' => CountryIso3Enum::PYF,
        'PG' => CountryIso3Enum::PNG,
        'PH' => CountryIso3Enum::PHL,
        'PK' => CountryIso3Enum::PAK,
        'PL' => CountryIso3Enum::POL,
        'PM' => CountryIso3Enum::SPM,
        'PN' => CountryIso3Enum::PCN,
        'PR' => CountryIso3Enum::PRI,
        'PS' => CountryIso3Enum::PSE,
        'PT' => CountryIso3Enum::PRT,
        'PW' => CountryIso3Enum::PLW,
        'PY' => CountryIso3Enum::PRY,
        'QA' => CountryIso3Enum::QAT,
        'RE' => CountryIso3Enum::REU,
        'RO' => CountryIso3Enum::ROU,
        'RS' => CountryIso3Enum::SRB,
        'RU' => CountryIso3Enum::RUS,
        'RW' => CountryIso3Enum::RWA,
        'SA' => CountryIso3Enum::SAU,
        'SB' => CountryIso3Enum::SLB,
        'SC' => CountryIso3Enum::SYC,
        'SD' => CountryIso3Enum::SDN,
        'SE' => CountryIso3Enum::SWE,
        'SG' => CountryIso3Enum::SGP,
        'SH' => CountryIso3Enum::SHN,
        'SI' => CountryIso3Enum::SVN,
        'SJ' => CountryIso3Enum::SJM,
        'SK' => CountryIso3Enum::SVK,
        'SL' => CountryIso3Enum::SLE,
        'SM' => CountryIso3Enum::SMR,
        'SN' => CountryIso3Enum::SEN,
        'SO' => CountryIso3Enum::SOM,
        'SR' => CountryIso3Enum::SUR,
        'SS' => CountryIso3Enum::SSD,
        'ST' => CountryIso3Enum::STP,
        'SU' => CountryIso3Enum::SUN,
        'SV' => CountryIso3Enum::SLV,
        'SX' => CountryIso3Enum::SXM,
        'SY' => CountryIso3Enum::SYR,
        'SZ' => CountryIso3Enum::SWZ,
        'TA' => CountryIso3Enum::TAA,
        'TC' => CountryIso3Enum::TCA,
        'TD' => CountryIso3Enum::TCD,
        'TF' => CountryIso3Enum::ATF,
        'TG' => CountryIso3Enum::TGO,
        'TH' => CountryIso3Enum::THA,
        'TJ' => CountryIso3Enum::TJK,
        'TK' => CountryIso3Enum::TKL,
        'TL' => CountryIso3Enum::TLS,
        'TM' => CountryIso3Enum::TKM,
        'TN' => CountryIso3Enum::TUN,
        'TO' => CountryIso3Enum::TON,
        'TR' => CountryIso3Enum::TUR,
        'TT' => CountryIso3Enum::TTO,
        'TV' => CountryIso3Enum::TUV,
        'TW' => CountryIso3Enum::TWN,
        'TZ' => CountryIso3Enum::TZA,
        'UA' => CountryIso3Enum::UKR,
        'UG' => CountryIso3Enum::UGA,
        'UK' => CountryIso3Enum::GBR,
        'UM' => CountryIso3Enum::UMI,
        'US' => CountryIso3Enum::USA,
        'UY' => CountryIso3Enum::URY,
        'UZ' => CountryIso3Enum::UZB,
        'VA' => CountryIso3Enum::VAT,
        'VC' => CountryIso3Enum::VCT,
        'VE' => CountryIso3Enum::VEN,
        'VG' => CountryIso3Enum::VGB,
        'VI' => CountryIso3Enum::VIR,
        'VN' => CountryIso3Enum::VNM,
        'VU' => CountryIso3Enum::VUT,
        'WF' => CountryIso3Enum::WLF,
        'WS' => CountryIso3Enum::WSM,
        'XK' => CountryIso3Enum::XXK,
        'YE' => CountryIso3Enum::YEM,
        'YT' => CountryIso3Enum::MYT,
        'YU' => CountryIso3Enum::YUG,
        'ZA' => CountryIso3Enum::ZAF,
        'ZM' => CountryIso3Enum::ZMB,
        'ZR' => CountryIso3Enum::ZAR,
        'ZW' => CountryIso3Enum::ZWE,
    ];
}
